### ISSUE TITLE
下拉刷新上拉加载更多

### ISSUE THREAD

**Issue by hrj303662813** [OCNYang/QBox#1]
不知作者有没有用到下拉刷新上拉加载更多，用哪个库比较不错？

**Comment by OCNYang** [comment]
具体的实现效果可以下载App查看。下拉刷新使用的官方的 SwipeRefreshLayout 。BaseRecyclerViewAdapterHelper 支持官方的刷新控件的，同时它提供的还有加载功能，同时加载动画可以自定义。
