### ISSUE TITLE
[help wanted]Is this a network problem or the project file(s) are invalid?

### ISSUE THREAD

**Issue by sysdl132** [OCNYang/QBox#16]
![image](https://user-images.githubusercontent.com/54708046/78084968-25179500-73ec-11ea-80cc-d8904cd31fcf.png)
Cannot add task 'wrapper' as a task with that name already exists.(build.gradle Line 35-37)

**Comment by sysdl132** [comment]
at:
```
task wrapper(type: Wr) {
    gradleVersion = '3.1'
}
```

**Comment by OCNYang** [comment]
这个问题应该是 Gradle 版本的问题。

你可以尝试改成新的写法：

```
wrapper {
    //configuration
}
```

**Comment by sysdl132** [comment]
![image](https://user-images.githubusercontent.com/54708046/78351672-c3b51900-75d9-11ea-9e41-f47244b2e653.png)
[Help wanted]

**Comment by sysdl132** [comment]
```
Caused by: org.gradle.api.internal.artifacts.ivyservice.DefaultLenientConfiguration$ArtifactResolveException: Could not resolve all files for configuration ':classpath'.

Caused by: org.gradle.internal.resolve.ModuleVersionResolveException: Could not resolve com.android.tools.build:gradle:3.0.1.

Caused by: org.gradle.internal.resolve.ModuleVersionResolveException: No cached version of com.android.tools.build:gradle:3.0.1 available for offline mode.
```

**Comment by OCNYang** [comment]
这仅仅是一个Gradle的配置问题。 这类问题很常见，你可以先通过百度寻求答案。
比如：  
[Could not resolve com.android.tools.build:gradle:3.4.1](https://blog.csdn.net/dyamail/article/details/90442646)  

[gradle 升级到 4.1 后出现的 Could not resolve com.android.tools.build:gradle:3.0.1](https://blog.csdn.net/weixin_33734785/article/details/87987962)

**Comment by sysdl132** [comment]
![image](https://user-images.githubusercontent.com/54708046/78627093-34eb1980-78c3-11ea-9ee5-44373d3fdb4d.png)

**Comment by sysdl132** [comment]
尝试编辑：
![image](https://user-images.githubusercontent.com/54708046/78632112-bc8b5500-78d0-11ea-90b3-0b1494375baf.png)

**Comment by sysdl132** [comment]
终于知道了：
![image](https://user-images.githubusercontent.com/54708046/79041798-21261700-7c25-11ea-9159-31eb7da36b3b.png)
我按了一个不该按的开关，会禁止网络
