### ISSUE TITLE
我通过https://mobile.baidu.com/item?type=soft&docid=21930773下载的APP直接闪退

### ISSUE THREAD

**Issue by lovewysy** [OCNYang/QBox#17]

**Comment by OCNYang** [comment]
请尝试下面链接下载：  
地址一：[http://d.firim.info/qbox](http://d.firim.info/qbox)
地址二：[https://raw.githubusercontent.com/OCNYang/QBox/master/apk/QBox.apk](https://raw.githubusercontent.com/OCNYang/QBox/master/apk/QBox.apk)

**Comment by lovewysy** [comment]
> 请尝试以下链接下载：
> 地址一：[http](http://d.firim.info/qbox) ://d.firim.info/qbox
> 地址二：[https](https://raw.githubusercontent.com/OCNYang/QBox/master/apk/QBox.apk) : //raw.githubusercontent.com/OCNYang/QBox/master/apk/QBox.apk[](https://raw.githubusercontent.com/OCNYang/QBox/master/apk/QBox.apk)

还是一样闪退，算了这个我有空下载源码调试一下好了！

**Comment by OCNYang** [comment]
远程数据的问题，现在已能正常使用
