### ISSUE TITLE
作者有打算开源的计划吗？

### ISSUE THREAD

**Issue by tianzry** [OCNYang/QBox#2]
Android开发新手，看了项目最终的效果，感觉很好，想要学习一下，作者有开源的计划吗？谢谢

**Comment by OCNYang** [comment]
现在项目还有  天气  模块没有完成，在项目的功能在迭代完整后，第一时间放在 Github 上。（最近在忙公司项目，我会加快的）

**Comment by tianzry** [comment]
@OCNYang 期待，感谢。也可以先放一部分呀，迫不及待学习一下

**Comment by KingLanding94** [comment]
同样期待！☺

**Comment by OCNYang** [comment]
@tianzry @KingLanding94

**Comment by tianzry** [comment]
@OCNYang 感谢
