### ISSUE TITLE
主导航页面（设计思路）

### ISSUE THREAD

**Issue by ImAlipay** [OCNYang/QBox#5]
导航页是用activity实现的吗？

**Comment by OCNYang** [comment]
查看代码 com.ocnyang.qbox.app.module.mains.MainsActivity;（及其父类） 或许你能找到你想要的答案。
基本方式就是在切换不同页面模块时，来控制对应的Fragment的切换（判断、显示、隐藏等），也是我们平时比较常用的方式。查看源码是比较清晰的，你可以仔细研究下，有什么困惑可以继续探讨.
