### ISSUE TITLE
在星座运势里面你默认是水瓶座，当我换一个其他星座的时候其他的fragment里面的值没有遍，还是水瓶座，需要再点一下其他星座才变。

### ISSUE THREAD

**Issue by SoulEaterVTT** [OCNYang/QBox#7]

**Comment by OCNYang** [comment]
这里叙述一下星座运势的整体逻辑：
1. 星座运势页面，进入时默认显示的是“用户个人信息 / 星座”设置的星座；如果没有设置，默认“水瓶座”；
2. 星座运势页面可以查询其他星座，但是设置的星座没有改变，下次进入还是会显示用户信息的星座；如果想改变，请修改个人信息里的星座设置；
3. 发现模块 / 今日星座运势 也是根据 “用户个人信息里的星座” 显示的，刚才发现这里的星座不会改变，是取SP的值传错了，已经 commit。
